### ISSUE TITLE
Metadata Collection Overlap in Benchmark Role

### ISSUE THREAD

**Issue by learnitall** [cilium/scaffolding#40]
We have the `metadata.yaml` task file, which collects metadata prior to running benchmarks. Some of the tasks within it are re-run within the `datapath.yml` or the `agent.yml` playbooks. I think we should remove this overlap, so we don't have two competing methods of metadata collection.

Ex: 

https://github.com/cilium/scaffolding/blob/main/roles/benchmarks/tasks/metadata.yml#L40=
https://github.com/cilium/scaffolding/blob/main/roles/benchmarks/tasks/datapath.yml#L23=

Both get the kernel

**Comment by jtaleric** [comment]
ha! I just noticed this, good catch!
