### ISSUE TITLE
Race condition in DeleteResourceAndWaitGone

### ISSUE THREAD

**Issue by marseel** [cilium/scaffolding#76]
Currently DeleteResourceAndWaitGone:
- Opens watch to wait for deleted resource (in separate goroutine)
- Deletes resource

This can cause a race condition where the resource is deleted and never observed on watch. 
We should wait for cache sync before deleting the resource. 
We can achieve it by adding precondition that will signal sync happened: [precondition code](https://github.com/kubernetes/client-go/blob/04ef61f72b7bc5ae6efef4e4dc0001746637fdb3/tools/watch/until.go#L137)

**Comment by learnitall** [comment]
I took a look at this earlier today, and I think we should just use a foreground delete and skip out on using the watcher altogether. It might simplify things a bit and should give us the same result of being able to delete something and wait for it to be gone. What do you think @marseel?
